config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :questions do
    member do
      patch 'upvote'
      patch 'downvote'
    end
    resources :answers do
      member do
        patch 'upvote'
        patch 'downvote'
      end
    end
  end

  root 'questions#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  validates_presence_of :title, :content

  belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers, dependent: :destroy

  validates_presence_of :title, :content
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  def self.get_quote
    response = HTTParty.get "https://api.github.com/zen", :headers=> { "User-Agent" => ENV['username'], "Authorization" => "token #{ENV['token']}" }
    response.body
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def new
  end

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html {
          redirect_to question_path(@question)
        }
        format.js {}
      else
        format.html {
          render 'questions/show'
        }
        format.js {}
      end
    end
  end

  def upvote
    @answer = Answer.find(params[:id])
    @question = Question.find(params[:question_id])
    @answer.vote += 1
    @answer.save
    respond_to do |format|
      format.html{
        redirect_to question_path(@question)
      }
      format.js {}
    end
  end

  def downvote
    @answer = Answer.find(params[:id])
    @question = Question.find(params[:question_id])
    @answer.vote -= 1
    @answer.save
    respond_to do |format|
      format.html{
        redirect_to question_path(@question)
      }
      format.js {}
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:title, :content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all.order(vote: :desc)
    @question = Question.new
    @quote = Quote.get_quote
  end

  def new
    redirect_to questions_path
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers.order(vote: :desc)
    @answer = Answer.new
  end

  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html {
          redirect_to question_path(@question), notice: 'Question was successfully saved'
        }
        format.js {}
      else
        format.html {
          render 'index'
        }
        format.js {}
      end
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    if @question.update_attributes(question_params)
      redirect_to question_path(@question)
    else
      render :edit
    end
  end

  def upvote
    @question = Question.find(params[:id])
    @question.vote += 1
    @question.save
    @question_id = @question.id
    respond_to do |format|
      format.html{
        redirect_to questions_path
      }
      format.js {}
    end
  end

  def downvote
    @question = Question.find(params[:id])
    @question.vote -= 1
    @question.save
    respond_to do |format|
      format.html{
        redirect_to questions_path
      }
      format.js {}
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to questions_path
  end

  private

  def question_params
    params.require(:question).permit(:title, :content)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_answer.html.erb
<div id="<%= answer.id %>" data-vote-count="<%= answer.vote %>">
<p>Title</p>
<p><%= answer.title %></p>
<p>Content</p>
<p><%= answer.content %></p>
<p class="vote">Vote: <%= answer.vote %></p>
<%= link_to 'Upvote', upvote_question_answer_path(@question, answer), remote: true, method: :patch %>
<%= link_to 'Downvote', downvote_question_answer_path(@question, answer), remote: true, method: :patch %>
<hr />
</div>

app/views/answers/_form.html.erb
<h1>New Answer</h1>
<%= form_for [@question, @answer], remote: true do |f| %>
<%= f.label :title %>
<p>
<%= f.text_field :title %>
</p>
<%= f.label :content %>
<p>
<%= f.text_area :content, rows: 8, cols: 40, class: "to-markdown" %>
</p>
<h1>Preview Area</h1>
<p class="preview-area"></p>

<%= f.submit %>
<% end %>

app/views/answers/create.js.erb
$('.answers').append("<%= j (render @answer) %>");

app/views/answers/downvote.js.erb
var $currentDiv = "div#" + "<%= (@answer.id) %>";
var currentElementVoteCount = parseInt(<%= @answer.vote %>);
var nextElementVoteCount = function(){ return parseInt($($currentDiv).next().attr("data-vote-count"))};
var previousElementVoteCount = function(){ return parseInt($($currentDiv).prev().attr("data-vote-count"))};

$("#" + "<%= (@answer.id) %>" + " .vote").text("Vote: " + "<%= (@answer.vote) %>");
$($currentDiv).attr("data-vote-count", "<%= @answer.vote %>")
while (currentElementVoteCount < nextElementVoteCount()) {
  $($currentDiv).insertAfter($($currentDiv).next());
}

app/views/answers/upvote.js.erb
var $currentDiv = "div#" + "<%= (@answer.id) %>";
var currentElementVoteCount = parseInt(<%= @answer.vote %>);
var nextElementVoteCount = function(){ return parseInt($($currentDiv).next().attr("data-vote-count"))};
var previousElementVoteCount = function(){ return parseInt($($currentDiv).prev().attr("data-vote-count"))};

$($currentDiv).attr("data-vote-count", "<%= @answer.vote %>");
$("#" + "<%= (@answer.id) %>" + " .vote").text("Vote: " + "<%= (@answer.vote) %>");
while (currentElementVoteCount > previousElementVoteCount()) {
  $($currentDiv).insertBefore($($currentDiv).prev());
}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="markDownApp">
<head>
  <title>DbcOverflow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p><%= notice %></p>
<p><%= alert %></p>
<p><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></p>
<%= yield %>
</body>
</html>

app/views/questions/_form.html.erb
<div ng-controller="markDownController">
  <h2>New Question</h2>
  <%= form_for @question, remote: true do |f| %>
    <%= f.label :title %>
  <p>
  <%= f.text_field :title %>
  </p>
  <%= f.label :content %>
  <p>
  <%= f.text_area :content, rows: 8, cols: 40, class: "to-markdown", "ng-model" => "inputText" %>
  </p>
  <h2>Preview Area</h2>
  <p ng-bind-html="parseInputText()"></p>
</div>
<%= f.submit %>
<% end %>

app/views/questions/_question.html.erb
<div id="<%= question.id %>" data-vote-count="<%= question.vote %>">
<p>Question: <%= question.title %></p>
<p class="vote">Vote: <%= question.vote %></p>
<%= link_to 'Upvote', upvote_question_path(question), remote: true, method: :patch %>
<%= link_to 'Downvote', downvote_question_path(question), remote: true, method: :patch %>
<%= link_to 'Show', question_path(question) %>
<%= link_to 'Edit', edit_question_path(question) %>
<hr />
</div>

app/views/questions/create.js.erb
$('.questions').append("<%= j (render @question) %>");

app/views/questions/downvote.js.erb
var $currentDiv = "div#" + "<%= (@question.id) %>";
var currentElementVoteCount = parseInt(<%= @question.vote %>, 10);
var nextElementVoteCount = function(){ return parseInt($($currentDiv).next().attr("data-vote-count"))};
var previousElementVoteCount = function(){ return parseInt($($currentDiv).prev().attr("data-vote-count"))};

$("#" + "<%= (@question.id) %>" + " .vote").text("Vote: " + "<%= (@question.vote) %>")
$($currentDiv).attr("data-vote-count", "<%= @question.vote %>")
while (currentElementVoteCount < nextElementVoteCount()) {
  $($currentDiv).insertAfter($($currentDiv).next());
}

app/views/questions/edit.html.erb
<h1>Edit page</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>DBC Overflow - <%= @quote %></h1>
<div class="questions">
<%= render @questions %>
</div>
<%= render 'form' %>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>
<hr />
<h2><%= @question.content %></h2>
<%= link_to 'Back', questions_path %>
<%= link_to 'Delete', question_path(@question), method: :delete, data: { confirm: 'Are you sure?' } %>
<h2>Answers</h2>
<div class="answers">
<%= render @answers %>
</div>
<%= render 'answers/form' %>

app/views/questions/upvote.js.erb
var $currentDiv = "div#" + "<%= (@question.id) %>";
var currentElementVoteCount = parseInt(<%= @question.vote %>);
var nextElementVoteCount = function(){ return parseInt($($currentDiv).next().attr("data-vote-count"))};
var previousElementVoteCount = function(){ return parseInt($($currentDiv).prev().attr("data-vote-count"))};

$("#" + "<%= (@question.id) %>" + " .vote").text("Vote: " + "<%= (@question.vote) %>");
$($currentDiv).attr("data-vote-count", "<%= @question.vote %>");
while (currentElementVoteCount > previousElementVoteCount()) {
  $($currentDiv).insertBefore($($currentDiv).prev());
}